publishDir = "docs"
# baseURL = 'https://aardwolverine.github.io/consultancy-site'
baseURL = 'https://acadsys.com.au'
languageCode = 'en-us'

title = "Academic Systems Consulting"
theme = "quint"

[params]
numImages = 10
css = ["css/custom.css"]
# Add your reCAPTCHA site key here (set on deploy to avoid exposing keys in source)
recaptcha_site_key = "6Ldr8JIsAAAAAFMyzWwB5CSqpgoI8EFgU6rtru8H"
# Google Analytics measurement id (set this to enable gtag events)
ga_measurement_id = "G-R57L0QB0EF"

[author]
  name = "Academic Systems Consulting"
  image = "/images/logo/logo-light.png"
  email = "info@acadsys.com.au"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changeFreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

enableGitIbfo = true

[frontmatter]
  lastmod = ['lastmod', ':git', 'publishDate', 'date']
